# Generated by Django 5.2.8 on 2025-11-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='voter_user_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('voter_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='voter_profile_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField()),
                ('gender', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('aadhaar_number', models.BigIntegerField()),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('select', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.voter_user_model')),
            ],
        ),
    ]
