# Generated by Django 5.2.8 on 2025-11-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter_profile_model',
            old_name='select',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='voter_user_model',
            name='voter_id',
            field=models.CharField(max_length=50),
        ),
    ]
